### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by jvazquez96** [jvazquez96/Perritos-app#13]
Change the order of the buttons (Accept/Delete) in pet/event/news/product addactivity.
Also change the position of the back button in each detail activity and add a background to the each text. See image: 
<img width="405" alt="screen shot 2017-05-04 at 10 47 50 pm" src="https://cloud.githubusercontent.com/assets/9115166/25733158/01bcb182-311c-11e7-97b6-5cefa632a636.png">

**Comment by alextrujillo4** [comment]
Done ! B-)
